# Generated by Django 5.2.17 on 2026-09-20 16:35

import django.db.models.deletion
import sync.snapshots
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('done', 'done')], default=sync.snapshots.TaskStatus['OPEN'], max_length=16)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('todoist', 'Todoist')], max_length=32)),
                ('account_label', models.CharField(max_length=200)),
                ('config', models.JSONField(default=dict)),
                ('cursor', models.JSONField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'account_label'), name='uniq_connection_account')],
            },
        ),
        migrations.CreateModel(
            name='InboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('todoist', 'Todoist')], max_length=32)),
                ('delivery_id', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['processed_at', 'received_at'], name='idx_inbox_pending')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'delivery_id'), name='uniq_inbox_delivery')],
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbox_op_id', models.UUIDField()),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('todoist', 'Todoist')], max_length=32)),
                ('op', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('attempts', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sync.task')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxOp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('todoist', 'Todoist')], max_length=32)),
                ('op', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_ops', to='sync.task')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='idx_outbox_claimable')],
            },
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('todoist', 'Todoist')], max_length=32)),
                ('external_id', models.CharField(max_length=200)),
                ('last_seen_hash', models.CharField(blank=True, max_length=64)),
                ('last_pushed_hash', models.CharField(blank=True, max_length=64)),
                ('canonical_version_synced', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sync.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_link_provider_external'), models.UniqueConstraint(fields=('task', 'provider'), name='uniq_link_task_provider')],
            },
        ),
    ]
